[versions]
agp = "8.7.3"
kotlin = "2.3.20"
coreKtx = "1.13.1"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.0"
activity = "1.9.2"
lifecycle = "2.8.7"
timber = "5.0.1"
coroutines = "1.9.0"
inskmpVersion = "2.1.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

inskmp-camera = { group = "com.arashivision.sdk", name = "sdk-camera", version.ref = "inskmpVersion" }
inskmp-media = { group = "com.arashivision.sdk", name = "sdk-media", version.ref = "inskmpVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
